@startuml
'https://plantuml.com/class-diagram

abstract class GeradorDocumento{
+ gerarDocumento(): void
+ buscarDados(): void
+ montarCabecalho(): void
+ abstract gerarCorpoDocumento(): void
+ assinarDigitalmente(): void
+ disponibilizarDownload(): void
}

class Declaracao extends GeradorDocumento{
+ gerarCorpoDocumento(): void
}
class Historico extends GeradorDocumento{
+ gerarCorpoDocumento(): void
}
class Certificado extends GeradorDocumento{
+ gerarCorpoDocumento(): void
}


@enduml