@startuml
'https://plantuml.com/class-diagram

interface PromocionalStrategy{
    + aplicar(valor:double) : double
}

class CalculadoraValor{
    - politicaStrategy: PromocionalStrategy
    + setStrategy(politica: PromocionalStrategy): void
    + calcularValor(valorBase: double): double
}

class DescontoPercentual implements PromocionalStrategy{
    -percentual: double
    + aplicar() : void
}

class Cashback implements PromocionalStrategy{
    -percentual: double
    + aplicar() : void
}

class FreteGratis implements PromocionalStrategy{
    - valorFrete: double
    + aplicar() : void
}
CalculadoraValor o-- PromocionalStrategy

@enduml