@startuml
'https://plantuml.com/class-diagram

class Pausado
class Parado
class Reproduzindo
interface PlayerState
class Player{
- PlayerState estado
}

PlayerState <|-- Pausado
PlayerState <|-- Parado
PlayerState <|-- Reproduzindo

@enduml