@startuml
'https://plantuml.com/class-diagram
class ConfiguracaoSingleton(){
    {static} - instance: ConfiguracaoSingleton
    - urlBanco: String
    - usuario: String
    - senha: String
    - portaServidor: int
    - idiomaPadrao: String

    -ConfiguracaoSingleton(): void
    {static} + getInstance(): Singleton

    +Getters e Setters()
}

@enduml