@startuml
'https://plantuml.com/class-diagram

interface Notificador{
    +notificar(): void
}

class EmailAdapter implements Notificador{
+ notificar(): void
}

class SmsAdapter implements Notificador{
+ notificar(): void
}
class PushAdapter implements Notificador{
+ notificar(): void
}

class SistemaNotificacao{
- notificador: Notificador
+ enviarNotificacao():void
}

SistemaNotificacao o--> Notificador

@enduml